### PR TITLE
Run representer on all exercises in CI

### PR DESCRIPTION
**Pull request by angelikatyborska**
WIP

### CODE REVIEW

**Comment by jiegillet** [comment]
I'm not convinced we should use git submodules for the CI.
On on the Elm Analyzer repo, we have [these lines](https://github.com/exercism/elm-analyzer/blob/e431d916e1129d691c99033abd2b216722334bb5/.github/workflows/elm_tests.yml#L149-L177) to check out the analyzer, then the repo in some subdirectory (effectively, same result as a submodule but much cleaner) and then run a script for running the analyzer on the repo exercises.
What do you think?

**Comment by jiegillet** [comment]
Nothing wrong per se, it's just kind of a pain to keep up to date, the command is long, and even if we don't care about keeping it up to date it's still kind of noisy in `git status`.

**Comment by angelikatyborska** [comment]
> the command is long

This one: `git submodule update --recursive --remote`? I never use that. I just `cd elixir; git pull; cd ..; git add .` 😁 

I want a solution where I can run all the tests locally as well as in CI, and it should be reasonably fast locally. 

If I see correctly, the elm analyzer accepts the path to the elm repo as an argument? I guess I can rewrite the Elixir tooling to do the same.

**Comment by angelikatyborska** [comment]
On second thought, I'm not crazy about the idea of having a clean state of my elixir repo locally to run analyzer/representer tests 🤔

**Comment by angelikatyborska** [comment]
Blocked by https://github.com/exercism/elixir-representer/pull/101

**Review by jiegillet — APPROVED** [review]
Seems to work, and code looks good :)

Next step, if we want to do that, is to call the representer from the main elixir repo to check new contributions. We can probably checkout the representer repo, checkout the submodule to the branch of the PR and run the same script.

**Comment by angelikatyborska** [comment]
That sounds like a nice idea, but maybe it would be possible to just trigger the CI on elixir-representer main branch whenever the CI on elixir main branch runs?

**Comment by jiegillet** [comment]
I haven’t done anything like that before, but sure if it’s possible it’s a good option.

**Pull request merged**
